@startuml 房东操作类图

skinparam shadowing false
skinparam defaultFontName "微软雅黑"

class  用户{
    - 账号
    - 密码
}



class 房东{
    - 房源信息
    - 评价信息
    - 收益
    
    # 上架房源()
    # 更新房源信息()
    # 下架房源()
    # 退款请求处理()
}

class 上架房源{
    # 填写房源信息()
    # 填写价格()
}

class 更新房源信息{
    # 修改价格()
    # 修改房间设施()
}

class 下架房源{
    # 提交下架申请()
}

class 退款请求处理{
    # 同意退款()
    # 申请第三方介入处理()
}








房东 -up-|> 用户

房东 ..> 上架房源
房东 ..> 更新房源信息
房东 ..> 下架房源
房东 ..> 退款请求处理







@enduml