@startuml
class  用户{
    - 账号
    - 密码

}



class 房客{
    - 余额
    - 预订信息
    
    # 房间检索()
    # 房间预订()
    # 订单评价()
}

class 检索{
    # 模糊检索()
    # 精确检索()
}

class 预订{
    # 修改余额()
    # 修改预订信息()
}

class 评价{
    # 输入评价文本()
}

class 模糊检索{
    # 根据推荐算法展示房源信息()
}

class 精确检索{
    # 根据用户输入条件返回房源信息()
}






房客 -up-|> 用户

房客 ..> 检索
房客 ..> 预订
房客 ..> 评价

模糊检索 -up-|> 检索
精确检索 -up-|> 检索






@enduml