@startuml 注册类图

skinparam shadowing false

class 用户 <<注册子系统>>{
    - 账号
    - 密码
    - 手机号
    - 邮箱

    # 注册账号()
    # 接收注册结果()
}

class 注册系统 {
    # 账号设置()
    # 密码设置()
    # 手机号设置()
    # 邮箱设置()
    # 返回注册信息()
}

注册系统 "1" -up- "1" 用户

@enduml
