@startuml
class  登录子系统{
    - 账号
    - 密码

    # 输入账号()
    # 输入密码()
    # 忘记密码()

}

class 登录控制 {
    
    # 密码验证()

    # 通过手机号重新设置密码()
    # 通关邮箱重新设置密码()
    # 返回信息()
}

class 用户{

}

class 房东 {
    - 房东信息
}
class 房客{
    - 房客信息
}

登录子系统 "1" -down- "1" 登录控制

登录控制 "1" -down- "n" 用户

房东 -up-|> 用户
房客 -up-|> 用户







@enduml