@startuml 房东上架房源活动图

skinparam shadowing false

|用户|
start
:进入房源信息提交界面]
:填写房源信息表格]
:点击提交按钮]
|系统|
if(审核房源信息是否合格)then(no)
    :显示房源信息不合格]
    |用户|
    :信息提交失败]
    stop
else(yes)
    |系统|
    :格式化房源信息]
    |数据库|
    :将房源信息添加入相应数据库]
    |系统|
    :显示房源信息上传成功]
    |用户|
    :房源信息提交成功]
    stop
endif
@enduml