@startuml 房客订房活动图

skinparam shadowing false

|用户|
start
:进入搜索界面]
:输入关键词]
:点击搜索按钮]
|系统|
:搜索引擎获得关键词]
:进入数据库]
|数据库|
:数据检索]
:信息筛选]
|系统|
:向房客显示搜索结果(可订民宿列表)]
|用户|
:挑选感兴趣的民宿]
|系统|
:获取用户的查看需求]
|数据库|
:查询相应民宿]
:获取民宿的具体信息]
|系统|
:向房客显示该民宿的具体信息]
|用户|
:查看该民宿的具体信息]
if(决定订购房屋)then(yes)
|用户|
:填写订购信息]
|系统|
:核实订单]
|数据库|
:修改数据库该民宿信息]
|系统|
:提示用户订房成功]
|用户|
stop
else(no)
|用户|
stop
@enduml