@startuml 房客登录活动图

skinparam shadowing false
skinparam defaultFontName "微软雅黑"

|用户|
start
:点击登录]
if(已有帐号)then(yes)
    :输入用户名]
    :输入密码]
else(no)
    :注册]
    repeat
        :输入新用户名]
        |系统|
        :验证注册信息]
        |用户表|
        :查询用户名]
    repeat while (用户名已被注册)
    |用户|
    :输入密码]
    :再次输入确认密码]
    :输入邮箱号]
    |系统|
    :向该邮箱号发送验证码]
    |用户|
    :输入验证码]
    :提交注册信息]
    |系统|
    :传送注册信息]
    |用户表|
    :将新用户注册信息添加入库]
endif
|用户|
:验证登录信息]
|用户表|
if(用户名密码正确)then(yes)
    |系统|
    :登陆成功，进入主界面]
    |用户|
    :继续操作]
    stop
else(no)
    |系统|
    :登陆失败]
    |用户|
    :重新登录]
    stop
endif
@enduml