@startuml 房源管理活动图

skinparam shadowing false

|用户|
start
:进入房源信息管理界面]
:选择需要操作的房源]
|系统|
if(判断房源是否可以修改)then(no)
    :显示房源信息修改失败]
    |用户|
    :修改操作失败]
    end
else(yes)
    |系统|
    :显示房源可以修改]
    |用户|
    :更新房源信息(修改价格，更新信息，下架)]
    |系统|
    :获取房东修改指令]
    |数据库|
    :检索相应房源]
    :根据用户指令进行修改(修改价格，更新信息，下架)]
    if(修改成功)then(no)
        |系统|
        :提示房东修改失败]
        |用户|
        :修改操作失败]
        end
    else(yes)
        |系统|
        :显示房东修改成功]
        |用户|
        :修改成功]
        stop
    endif
endif
@enduml