@startuml 用例图

skinparam shadowing false

actor 房客
actor 房东
actor 用户

用户 <|-- 房客
用户 <|-- 房东

(检索民宿) <|-- (精确检索)
(检索民宿) <|-- (模糊检索)

(注册) <|-left- (邮箱注册)
(注册) <|-up- (手机号注册)

:用户: -left-> (注册)
:用户: -right-> (登录)
:用户: -up-> (订单管理)

:房客: --> (预定民宿)
:房客: --> (检索民宿)

:房东: --> (上架民宿)
:房东: -left-> (民宿管理)

(预定民宿) ..> (优惠预订) : extends
(登录) .> (找回密码) : extends

(上架民宿) ..> (房东信息审核) : include
(上架民宿) ..> (房源信息提交) : include

(民宿管理) ..> (修改价格) : include
(民宿管理) ..> (更新房源信息) : include
(民宿管理) ..> (下架) : include


@enduml